[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "chess-engine"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12.7,<4"
chess = ">=1.11.0,<2"
black = ">=24.8.0,<25"
ipykernel = ">=6.29.5,<7"
